# This is a basic workflow to help you get started with Actions

name: Clean workflow

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    jobs-one:
      name: Clean
      runs-on: ubuntu-latest
      steps: 
        - name: testing
          uses: appleboy/ssh-action@master
          with: 
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.POST }}
            script: |
              unalias rm
              rm -rf cmsc389T-web-template


